### PR TITLE
Make generateMax and generateBetween produce uniform output

### PR DESCRIPTION
**Pull request by dfoxfranke**
Fix issue #12.

### CODE REVIEW

**Comment by solatis** [comment]
This is quite a common strategy to avoid modulus bias. +1 for this merge, it's weird that a crypto number generator generates biased numbers.

**Comment by vincenthz** [comment]
I've pulled the code and I had to revert, as it was creating a spinner in the test. I'ld be happy to pull a fixed version

**Comment by solatis** [comment]
I'll make an attempt at fixing this somewhere next week.

On Saturday, January 17, 2015, Vincent Hanquez <notifications@github.com>
wrote:

> I've pulled the code and I had to revert, as it was creating a spinner in
> the test. I'ld be happy to pull a fixed version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vincenthz/hs-crypto-numbers/pull/14#issuecomment-70371457>
> .
>


-- 
Sent from my iPhone

**Comment by dfoxfranke** [comment]
I'm able to reproduce the spinning test. I'll track it down if solatis doesn't get to it first.

**Pull request closed without merging**
